### ISSUE TITLE
Display of images is not dynamic

### ISSUE THREAD

**Issue by Qixin913** [WassimTenachi/PhySO#18]
I'm having some problems running the code, after plt.show draws a graph, the code doesn't run, what can I do to make it draw dynamically? I wonder if I am the only one with that problem? (btw, My computer is a MacBook air with M1.)

**Comment by WassimTenachi** [comment]
Hi @Qixin913,

If you run the example in the demo folder, the monitoring plots should not be shown at all but saved in .png, .pdf and .csv files and automatically be updated.
Can you confirm that you do not encounter this issue with the demo files ?

If not, can you give the code that produces this issue.

Wassim

PS: using Mac M1 is OK, physo has been extensively tested on this platform

**Comment by WassimTenachi** [comment]
Hi @Qixin913, can you confirm that you were able to access monitoring plots so I can close this thread ?

**Comment by Qixin913** [comment]
Hi @WassimTenachi , The monitoring plots problem was solved, Thank u very much again!

**Comment by WassimTenachi** [comment]
Sure no problem ! :)
