### ISSUE TITLE
RuntimeError: Failed to process string with tex because latex could not be found

### ISSUE THREAD

**Issue by ftry** [WassimTenachi/PhySO#21]
Unable to make visualisation plots.
Unable to save pareto figure.
“Unable to save last plots and data before stopping.”Does this mean that the next round of learning cannot be started!

Because I am training on the server, I want to not show the pictures of each step, but save the pictures. I am more concerned about the final result, but it seems that without visualization, training cannot be performed. is that so?

Fallow my result and  warning: 
UserWarning: Can not import display packages. warnings.warn("Can not import display packages.")
-> Raw expression : 
      2     
     m      
────────────
     1      
m⋅────────⋅1
         2  
  g⋅z + v   

Best of epoch at R=0.655170
-> Raw expression : 
         ⎛  1     v⎞
m⋅v⋅v⋅cos⎜───── + ─⎟
         ⎜⎛v⋅v⎞   v⎟
         ⎜⎜───⎟    ⎟
         ⎝⎝g⋅z⎠    ⎠

Unable to make visualisation plots.
Unable to save pareto figure.
=========== Epoch 00006 ===========
-> Time 2.59 s

Overall best  at R=1.000000
-> Raw expression : 
      2     
     m      
────────────
     1      
m⋅────────⋅1
         2  
  g⋅z + v   

Best of epoch at R=0.606942
-> Raw expression : 
   m   
───────
    v  
1⋅─────
  g⋅v⋅z

Unable to save last plots and data before stopping.

**Comment by leoyang-go** [comment]
same question ,but my Best of epoch always is R=0.00000

**Comment by ftry** [comment]
I resolve it by sudo yum install texlive texlive-dvipng!!!

**Comment by WassimTenachi** [comment]
Hey @leoyang-go, I suggest you create your own issue as it sounds like your problem is more profound then a monitoring plot problem related to a latex install issue.
