### ISSUE TITLE
trainning is wrong ,cant get the resuelt of model 

### ISSUE THREAD

**Issue by leoyang-go** [WassimTenachi/PhySO#22]
Hi Wassim
`Unable to make visualisation plots.
Unable to save pareto data.
Unable to save pareto figure.
=========== Epoch 65122 ===========
-> Time 4.61 s

Overall best  at R=0.000000
`
long time training,the overall best is abnormal!,what's wrong?
Can you take a look for me, thank you very much！

**Comment by WassimTenachi** [comment]
Hi @leoyang-go,

Did you run one of the demo notebook or you own custom code ? (Which of the demo notebooks causes this error ?)

Can you check that you are able to pass the units tests and share the resulting log ?

Wassim

**Comment by leoyang-go** [comment]
thanks for your anwser,the domo notebook can run successly,So i try to  run my own custom code.
I want to use physo to push down a mathematical model, the input is three-dimensional, the output is one-dimensional, but the input and output have dimensionless data, so I set the unit to [0,0,0] for the dimensionless data, I don’t know if this causes an error[](https://docs.google.com/document/d/1EvxAW3ayXt5O4P-x2TW-m9MkcWvxOEcIsQpma-NQGM4/edit?usp=sharing)

**Comment by WassimTenachi** [comment]
It looks like all candidate functions's reward are zeroed out because they do not satisfy units constraints.
Can you give the code you use to launch the run ?

The units should be set to dimensionless (eg. [0,0,0]) for y, all components of X, free constants and constants in your case ! 
I will be able to help more if you share your code ! :)
(It is also possible to deactivate units constraints altogether using a custom hyperparameter config)

**Comment by leoyang-go** [comment]
thanks for your answser! my code is in next line ,I simply changed the sr_demo to fit my data.

data_xgb = np.loadtxt('chassis_data/xgbt_data.txt')

data = data_xgb[np.where(np.logical_and(data_xgb[:, 2] < 0, data_xgb[:, 2] > -8))[0]]
data = data[np.where(abs(data[:, 2] - data[:, 0]) < 60)[0]]

br = data[:,0]  #/dimensionless
v = data[:,1]   #/ m*s-1
acc = data[:,2] #/ m*s-2
cmd = data[:,3] #/ dimensionless
X_array = np.stack((br, v,acc), axis=0)
m = 1.5
g = 9.8
y_array = cmd

expression, logs = physo.SR(X_array, y_array,
                            # Giving names of variables (for display purposes)
                            X_names = [ "br"       , "v"       ,"acc" ],
                            # Giving units of input variables
                            X_units = [ [0, 0, 0] , [1, -1, 0] ,[1, -2, 0]],
                            # Giving name of root variable (for display purposes)
                            y_name  = "cmd",
                            # Giving units of the root variable
                            y_units = [2, -2, 1],
                            # Fixed constants
                            fixed_consts       = [ 1.      ],
                            # Units of fixed constants
                            fixed_consts_units = [ [0,0,0] ],
                            # Free constants names (for display purposes)
                            free_consts_names = [ "Ts" ], #/ add Ts to satisfy units constraints
                            # Units offFree constants
                            free_consts_units = [ [0, 1, 0]  ],
)

**Comment by leoyang-go** [comment]
thanks for your answser! my code is in next line ,I simply changed the sr_demo to fit my data.

```
data_xgb = np.loadtxt('chassis_data/xgbt_data.txt')

data = data_xgb[np.where(np.logical_and(data_xgb[:, 2] < 0, data_xgb[:, 2] > -8))[0]]
data = data[np.where(abs(data[:, 2] - data[:, 0]) < 60)[0]]

br = data[:,0]  #/dimensionless
v = data[:,1]   #/ m*s-1
acc = data[:,2] #/ m*s-2
cmd = data[:,3] #/ dimensionless
X_array = np.stack((br, v,acc), axis=0)
m = 1.5
g = 9.8
y_array = cmd

expression, logs = physo.SR(X_array, y_array,
                            # Giving names of variables (for display purposes)
                            X_names = [ "br"       , "v"       ,"acc" ],
                            # Giving units of input variables
                            X_units = [ [0, 0, 0] , [1, -1, 0] ,[1, -2, 0]],
                            # Giving name of root variable (for display purposes)
                            y_name  = "cmd",
                            # Giving units of the root variable
                            y_units = [2, -2, 1],
                            # Fixed constants
                            fixed_consts       = [ 1.      ],
                            # Units of fixed constants
                            fixed_consts_units = [ [0,0,0] ],
                            # Free constants names (for display purposes)
                            free_consts_names = [ "Ts" ], #/ add Ts to satisfy units constraints
                            # Units offFree constants
                            free_consts_units = [ [0, 1, 0]  ],
)
```

**Comment by leoyang-go** [comment]
thanks for your anwser,if I set units to dimensionless,It seems to have encountered a new problem.
the traning process has been killed and the result miss a variable(acc) throughout the training process;
```
=========== Epoch 01865 ===========
-> Time 54.90 s

Overall best  at R=0.693840
-> Raw expression : 
                  0.5
      ⎛  1.0⋅Ts  ⎞   
1.0⋅v⋅⎜──────────⎟   
      ⎜⎛  1.0   ⎞⎟   
      ⎜⎜────────⎟⎟   
      ⎜⎜⎛  br  ⎞⎟⎟   
      ⎜⎜⎜──────⎟⎟⎟   
      ⎜⎜⎜⎛ Tm ⎞⎟⎟⎟   
      ⎜⎜⎜⎜────⎟⎟⎟⎟   
      ⎜⎜⎜⎜⎛br⎞⎟⎟⎟⎟   
      ⎜⎜⎜⎜⎜──⎟⎟⎟⎟⎟   
      ⎝⎝⎝⎝⎝v ⎠⎠⎠⎠⎠   

Best of epoch at R=0.688118
Killed
```
next line is my code.
```
data_xgb = np.loadtxt('chassis_data/xgbt_data.txt')

data = data_xgb[np.where(np.logical_and(data_xgb[:, 2] < 0, data_xgb[:, 2] > -8))[0]]
data = data[np.where(abs(data[:, 2] - data[:, 0]) < 60)[0]]

br = data[:,0]  #/dimensionless
v = data[:,1]   #/ m*s-1
acc = data[:,2] #/ m*s-2
cmd = data[:,3] #/ dimensionless
X_array = np.stack((br, v, acc), axis=0)
y_array = cmd 

print("data_size :",len(y_array))


expression, logs = physo.SR(X_array, y_array,
                            # Giving names of variables (for display purposes)
                            X_names = [ "br"       , "v"       ,"acc" ],
                            # Giving units of input variables
                            X_units = [ [0, 0, 0] , [1, -1, 0] ,[1, -2, 0]],
                            # Giving name of root variable (for display purposes)
                            y_name  = "cmd",
                            # Giving units of the root variable
                            y_units = [0, 0, 0],
                            # Fixed constants
                            fixed_consts       = [ 1.      ],
                            # Units of fixed constants
                            fixed_consts_units = [ [0,0,0] ],
                            # Free constants names (for display purposes)
                            free_consts_names = [ "Ts" ,"Tm"], #/ add Ts to satisfy units constraints
                            # Units offFree constants
                            free_consts_units = [ [0, 1, 0] ,[1, 0, 0] ],
)
```

**Comment by WassimTenachi** [comment]
This code runs fine on my side:
```
import physo
import numpy as np

br  = np.random.uniform(-1,1,100) #/dimensionless
v   = np.random.uniform(-1,1,100) #/ m*s-1
acc = np.random.uniform(-1,1,100) #/ m*s-2
cmd = np.random.uniform(-1,1,100) #/ dimensionless

X_array = np.stack((br, v, acc), axis=0)
y_array = cmd 

print("data_size :",len(y_array))


expression, logs = physo.SR(X_array, y_array,
                            # Giving names of variables (for display purposes)
                            X_names = [ "br"       , "v"       ,"acc" ],
                            # Giving units of input variables
                            X_units = [ [0, 0, 0] , [1, -1, 0] ,[1, -2, 0]],
                            # Giving name of root variable (for display purposes)
                            y_name  = "cmd",
                            # Giving units of the root variable
                            y_units = [0, 0, 0],
                            # Fixed constants
                            fixed_consts       = [ 1.      ],
                            # Units of fixed constants
                            fixed_consts_units = [ [0,0,0] ],
                            # Free constants names (for display purposes)
                            free_consts_names = [ "Ts" ,"Tm"], #/ add Ts to satisfy units constraints
                            # Units offFree constants
                            free_consts_units = [ [0, 1, 0] ,[1, 0, 0] ],
)
```

> thanks for your anwser,if I set units to dimensionless,It seems to have encountered a new problem. the traning process has been killed and the result miss a variable(acc) throughout the training process;

I've never encountered that before this is weird as physo checks that no nans are present in the data and candidate evaluation and monitoring are protected so as to not stop execution even in case of a failure.

> Killed

You had no other details ?
It might be because since run is very long the code and that RAM was exceeded, how much RAM do you have ?

**Comment by leoyang-go** [comment]
thanks!  After normalizing the input，There are very strange results,the result miss a variable(acc)and my computer ram is 32g。
```
=========== Epoch 01582 ===========
-> Time 1.57 s

Overall best  at R=0.676479
-> Raw expression : 
   ⎛                        0.5⎞
   ⎜   ⎛               1   ⎞   ⎟
sin⎜br⋅⎜v⋅1.0⋅v⋅v⋅v⋅───────⎟   ⎟
   ⎝   ⎝            v⋅v⋅v⋅v⎠   ⎠

Best of epoch at R=0.673909
-> Raw expression : 
   ⎛   ⎛    br   ⎞⎞
   ⎜   ⎜   ℯ     ⎟⎟
sin⎜log⎜─────────⎟⎟
   ⎜   ⎜⎛v⋅v⋅v⋅v⎞⎟⎟
   ⎜   ⎜⎜───────⎟⎟⎟
   ⎜   ⎜⎜      2⎟⎟⎟
   ⎝   ⎝⎝ (v⋅v) ⎠⎠⎠

```

**Comment by WassimTenachi** [comment]
It is not necessarily strange that acc does not appear, it just means that for now physo has not found it very useful to make it appear in order to produce an accurate expression.
This might be because acc has a very low impact on cmd compared to other more important variables such as v in your dataset. 
You should checkout issue #20 where this is discussed.
