### ISSUE TITLE
How can I add custom operator?

### ISSUE THREAD

**Issue by 1y9y9l4** [WassimTenachi/PhySO#23]
Hi Wassim,
Thanks for open source for this amazing tool. I found that physo.physym.functions.py contains a series of pre-defined operators for the regression process. I'd like to ask if user can introduce custom operations, such as 'erf' functions, to enrich the fitting capabilities.

**Comment by WassimTenachi** [comment]
Hi @1y9y9l4,

I will make a tutorial for how to do that in the future !
In the meantime you can just add your function by adding a line here below the line defining n4 in physo.physym.functions :
```
OPS_UNPROTECTED = [
       ...
       Token (name = "n4"     , sympy_repr = "n4"     , arity = 1 , complexity = 1 , var_type = 0, function = lambda x :torch.pow(x, 4)         ),
       Token (name = "erf"     , sympy_repr = "erf"    , arity = 1 , complexity = 1 , var_type = 0, function = torch.erf,
    ]
```

Sorry for the late response !

Wassim

**Comment by 1y9y9l4** [comment]
Thanks for your reply.
I added "erf" after "n4" as you said, and it gave the following error info:
`AssertionError: Failure to process units requirements of 79 token. Positions in batch = [ 22  24  32  41  42  51  61  70  92 108 117 118 127 129 155 159 160 171
 175 185 191 201 207 211 216 227 237 265 268 273 291 332 341 344 351 355
 366 376 386 395 423 432 443 444 456 502 505 514 526 571 577 579 588 596
 623 635 643 647 656 705 718 719 739 740 771 777 833 836 852 855 883 887
 891 895 925 937 945 979 992] ; positions in sequence = [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1] (no corresponding case found).`

I guess it's the unit processing problem of the custom function. After I rewirte line106, the program works:
`"UNARY_DIMENSIONLESS_OP"    : OpUnitsBehavior(behavior_id = 5 , op_names = ["sin", "cos", "tan", "exp", "log", "expneg", "logabs", "sigmoid", "tanh", "sinh", "cosh", "harmonic", "erf"]),`

Is this a correct modification?
Thanks again for you reply and this tool!

**Comment by WassimTenachi** [comment]
Yes @1y9y9l4, that is correct ! :)
I forgot to fill in the behavior of erf in the context of dimensional analysis ! Since it is dimensionless your modification is correct ! 
You can submit this addition of erf to the git if you want and I will gladly accept it !
