### ISSUE TITLE
FAIL: test_infix_repr

### ISSUE THREAD

**Issue by franfram** [WassimTenachi/PhySO#24]
Hello Wassim, amazing work you are doing here!

I've followed the installation instructions of the README, and I'm getting the following failed test when running `python -m unittest discover -p "*UnitTest.py"` :

```
FAIL: test_infix_repr (physo.physym.tests.program_display_UnitTest.DisplayTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/PhySO/physo/physym/tests/program_display_UnitTest.py", line 77, in test_infix_repr
    self.assertTrue(works_bool)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 70 tests in 27.472s

FAILED (failures=1)
```

Any idea how I can fix this?

Running on Pop OS 22.04

Cheers!

**Comment by WassimTenachi** [comment]
Hi @franfram,

This is probably  due to latex not being installed / available on your system.
I am working on instructions for how to do that properly on every system.
In the meantime, you can check out #16 and #21 ! ;)

Cheers.
Wassim

**Comment by franfram** [comment]
Thanks @WassimTenachi !
