### ISSUE TITLE
Minor changes?

### ISSUE THREAD

**Issue by jinghuazhao** [WassimTenachi/PhySO#26]
Thank you for making this availlable.

I got complaints about requirements.txt suggesting that pytorch there should be torch instead?

At the "Getting started" section, it might be helpful to add `import numpy as np` statement.

**Comment by WassimTenachi** [comment]
> 


Hi @jinghuazhao,

> I got complaints about requirements.txt suggesting that pytorch there should be torch instead?
It sounds like you tried to install the requirements file with pip instead of conda as pytorch is the right name with conda and torch the right name in pip.
More information here: https://pytorch.org/get-started/locally/
Can you try with this exact command ?
`conda install --file requirements.txt`

> At the "Getting started" section, it might be helpful to add `import numpy as np` statement.
Thanks I forgot that !

Wassim

**Comment by jinghuazhao** [comment]
Thanks -- it is good to know that.  I started off with conda install but diverted to pip due to failure with `conda activate` and I now stick to `conda install`.

I can largely run through codes in README.md but still have complaint "Can not import display packages." and will look at that later.

**Comment by WassimTenachi** [comment]
> Thanks -- it is good to know that. I started off with `conda install` but diverted to `pip install` due to failure with `conda activate` and I now stick to `conda install`.

A specific conda environment is better for physo as it uses dependencies with specific versions.
You can learn more about conda environment here: https://towardsdatascience.com/introduction-to-conda-virtual-environments-eaea4ac84e28

> I can largely run through codes in README.md (a ipynb better?) 

You can find the .ipynb corresponding to the getting started: [here](demo/demo_quick_sr.ipynb)

> but still have complaint "Can not import display packages." and will look at that later.

It sounds like latex is not available on your system.
You can refer to issues #16 #21 if your running a unix system or issues #5 #8 if your running windows.

**Comment by jinghuazhao** [comment]
I appeared ot have installed requirements_display1.txt but there was complaint about difference in zlib 2.7.1 header. I am running those within README.md after loading texlive on our system. Earlier I used pip install pdflatex which seemed successful. Yes, I found those demo/ directory which are very helpful.

**Comment by WassimTenachi** [comment]
> I appeared ot have installed requirements_display1.txt but there was complaint about difference in zlib 2.7.1 header. I just ran those within README.md after loading texlive on our system which gave pdf and png! Earlier I used pip install pdflatex which seemed successful. Yes, I found those demo/ directory which are very helpful and ran without issues.
> 
> Not es are kept for myself and our place here, https://cambridge-ceu.github.io/csd3/applications/PhySo.html.

That's great ! It sounds very useful ! :)

> Current errors,
> 
> -> Raw expression : 0.5 ⎛ ⎛ -1.0⎞ ⎛ 1 ⎞ 2⎞ x₀₀⋅⎜sin⎝ℯ ⎠⋅log⎜────⎟⋅1.0⋅-(c₀₀⋅c₀₁) ⎟ ⎜ ⎜ 1.0⎟ ⎟ ⎝ ⎝ℯ ⎠ ⎠
> 
> SR task started... 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 10000/10000 [00:04<00:00, 2325.25it/s] 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 10000/10000 [00:00<00:00, 81382.12it/s] Traceback (most recent call last): File "", line 17, in File "/rds/project/jmmh2/rds-jmmh2-projects/olink_proteomics/scallop/PhySO/physo/task/sr.py", line 247, in SR rewards, candidates = fit (X, y, run_config, File "/rds/project/jmmh2/rds-jmmh2-projects/olink_proteomics/scallop/PhySO/physo/task/fit.py", line 69, in fit hall_of_fame_R, hall_of_fame = learn.learner ( File "/rds/project/jmmh2/rds-jmmh2-projects/olink_proteomics/scallop/PhySO/physo/learn/learn.py", line 237, in learner run_logger.log(epoch = epoch, File "/rds/project/jmmh2/rds-jmmh2-projects/olink_proteomics/scallop/PhySO/physo/learn/monitoring.py", line 111, in log self.R_history_array = np.array(self.R_history) ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (13,) + inhomogeneous part.

This is puzzling, I never saw this error before.
Can you give the code that produced this error ?

**Comment by jinghuazhao** [comment]
Not quite sure if i missed anyting from code chunks the README.md -- see bottom of the page above for code list which I extracted.

**Comment by WassimTenachi** [comment]
Can you execute this [notebook](https://github.com/WassimTenachi/PhySO/blob/main/demo/demo_quick_sr.ipynb) and check if it works smoothly ?

**Comment by jinghuazhao** [comment]
Yes, both the .ipynb and .py in the demo/ directory run smoothly without problems. I haven't tried those in the two subdirectories.

**Comment by WassimTenachi** [comment]
In your code, I see that you are launching 3 physo runs one after the other with different parameters:

```
expression, logs = physo.SR(X, y,
                            X_units = [ [1, 0, 0] , [1, -1, 0] ],
                            y_units = [2, -2, 1],
                            fixed_consts       = [ 1.      ],
                            fixed_consts_units = [ [0,0,0] ],
                            free_consts_units  = [ [0, 0, 1] , [1, -2, 0] ],
)

expression, logs = physo.SR(X, y,
                            X_units = [ [1, 0, 0] , [1, -1, 0] ],
                            y_units = [2, -2, 1],
                            fixed_consts       = [ 1.      ],
                            fixed_consts_units = [ [0,0,0] ],
                            free_consts_units  = [ [0, 0, 1] , [1, -2, 0] ],
                            run_config = physo.config.config1.config1
)

expression, logs = physo.SR(X, y,
                            X_names = [ "z"       , "v"        ],
                            X_units = [ [1, 0, 0] , [1, -1, 0] ],
                            y_name  = "E",
                            y_units = [2, -2, 1],
                            fixed_consts       = [ 1.      ],
                            fixed_consts_units = [ [0,0,0] ],
                            free_consts_names = [ "m"       , "g"        ],
                            free_consts_units = [ [0, 0, 1] , [1, -2, 0] ],
                            op_names = ["mul", "add", "sub", "div", "inv", "n2", "sqrt", "neg", "exp", "log", "sin", "cos"]
)
```

I think this is what causes this bug.
This was not encountered before as the kernel is usually reseted between runs.
I will work on a fix, in the meantime, you can use physo by launching one run only.

**Comment by jinghuazhao** [comment]
Thank you!
