### ISSUE TITLE
Double requirement of matplotlib

### ISSUE THREAD

**Issue by M-Colley** [WassimTenachi/PhySO#31]
In the requirements.txt, there is matplotlib==3.5.1 and matplotlib

As the code is currently not working with matplotlib 3.7.0 and 3.7.1 due to a bug in that library, that you should be explicit in that file :) 

Kind regards

**Comment by WassimTenachi** [comment]
Hi @M-Colley,

Thank you for bringing the unnecessary double requirement to my attention !
Do you mean that you are unable to run physo with matplotlib 3.7.0 / 3.7.1 ?
I just tested it and it works on my machine.

Cheers.
Wassim

**Comment by M-Colley** [comment]
I recreated some of your demos in Google Colab and it doesn't work with the pre-installed 3.7.1 of matplotlib (some axes error when running the SR or fit method).

Kind regards

**Comment by WassimTenachi** [comment]
Thank you again for brining that to my attention @M-Colley.
I was able to reproduce the issue on colab only (it works fine on linux and OSX though).
I have a similar issue with matplotlib 3.5.1, were you able to resolve the issue with a specific version of matplotlib ?

**Comment by M-Colley** [comment]
Hey, yeah I was able to run it. I also had Latex installed using:

`!sudo apt-get install texlive-latex-extra texlive-fonts-recommended dvipng cm-super
!pip install latex`

I did have to downgrade to matplotlib 3.5.1 though to make it work, 3.7.1 did not work :)

**Comment by M-Colley** [comment]
One other quick question: 

if I have only one dimension as independent variable, which is the correct method to use?

`physo.SR`
or 
`physo.fit`

Based on the examples, I assume `physo.fit`? 

Kind regards!

**Comment by WassimTenachi** [comment]
> I did have to downgrade to matplotlib 3.5.1 though to make it work, 3.7.1 did not work :)

Weird I was able to make it work with 3.7.1 (even on colab) on my side...
I am going to leave a version free requirement for safety for now in case 3.5.1 is not available on some systems.

**Comment by M-Colley** [comment]
Thank you so much for your responses! That really helps a lot. 

Potentially, it would help users also to have the Colab in case you want to share it :)


Again, thank you and kind regards

**Comment by M-Colley** [comment]
One more question: why is `sympy == 1.10.1` required? Is support for newer versions planned (https://github.com/sympy/sympy/releases/tag/sympy-1.12)

**Comment by WassimTenachi** [comment]
> Potentially, it would help users also to have the Colab in case you want to share it :)
It's a good idea ! I will clean it a bit and share it ! :)

> One more question: why is `sympy == 1.10.1` required? Is support for newer versions planned ([sympy/sympy@`sympy-1.12` (release)](https://github.com/sympy/sympy/releases/tag/sympy-1.12))?
For no good reason, it is just required by safety in case a behavior is changed in the newer versions (I have tested physo with this version extensively)  but in principle yes it is compatible with newer versions !

**Comment by WassimTenachi** [comment]
I'm closing this thread but please feel free to ask any other questions or raise issues and I will gladly reopen it !
