### ISSUE TITLE
Support for Matrix or Tensor Symbolic Regression Tasks

### ISSUE THREAD

**Issue by Jamie-Z** [WassimTenachi/PhySO#33]
Hi Wassim!

It seems that the current version only supports scalar dependent variables in the training set. 
`assert len(y_target.shape) == 1, "y_target must have shape = (data_size,)"`

If there are any plans to support matrix or tensor variables as dependent variables (e.g. y_target.shape = (9600,3,3)) in symbolic regression tasks in future versions of the program? 

Thank you so much!

**Comment by WassimTenachi** [comment]
Hi @Jamie-Z,

Yes it is planned but it is very challenging so not for the immediate future !

Cheers.
Wassim

PS: I'm marking this issue as closed at it was just a simple feature request but please feel free to comment again if you have further questions !

**Comment by Jamie-Z** [comment]
Got it! Thanks a lot!
