### ISSUE TITLE
Requirements.txt change pytorch to torch

### ISSUE THREAD

**Issue by M-Colley** [WassimTenachi/PhySO#38]
Hey, I think in the `requirements.txt` you could change 

`pytorch >= 1.11.0`

to 

`torch >= 1.11.0`.

I got an installation error and also usually see that torch is used here.

Error:

> ERROR: Could not find a version that satisfies the requirement pytorch>=1.11.0 (from versions: 0.1.2, 1.0.2)
> ERROR: No matching distribution found for pytorch>=1.11.0

**Comment by WassimTenachi** [comment]
Hey @M-Colley,

`pytorch` works with conda install and `torch` with pip install.
Packages in `requirements.txt` are expected to be installed with conda following the standard installation procedure via:

```conda install --file requirements.txt```

Packages expected to be installed with pip are in `requirements_display2.txt` and this only concerns display packages.

```pip install -r requirements_display2.txt```

So this is normal !

Does this answer your question ?

Wassim

**Comment by M-Colley** [comment]
Yes, thank you! I indeed was working with pip...

Cheers
