### ISSUE TITLE
Issue with package_data parameter in setup.py causing installation error

### ISSUE THREAD

**Issue by pronoobe** [WassimTenachi/PhySO#45]
I've encountered an issue during installation where the `package_data` parameter in the `setup.py` file is causing an error. It appears that the description in the dictionary should not be an absolute path but should be a list of strings. When I modified it to an arbitrary list of strings, the installation proceeded without any errors.

This is the relevant part of the `setup.py` file that needs to be addressed:

```python
# Before modification
   package_data  = {
"physo": ["/benchmark/FeynmanDataset/*.csv"]
}

# After modification
package_data={
    'my_module': ['111', '222'],
}
```

Please consider making this adjustment to ensure smooth installations. Thank you!

**Comment by pronoobe** [comment]
??7傔?D3衭{*俘俔@***@***.***|!x??о瞂ftwn&?鼑  箱襒眘)喵  d?輑田璐Vm系y1太莭W棆鲾窓眙霿рd??e菄躞 tXF;驌

**Comment by WassimTenachi** [comment]
It looks like something went wrong with the encoding of the characters of your message, can you elaborate ?

**Comment by WassimTenachi** [comment]
Hi @pronoobe,

Please let me know if this fixed your issue so I can close this thread.
Thanks!

**Comment by WassimTenachi** [comment]
Hi @pronoobe,

I will close this thread now but feel free to re-open if you need further assistance !
Cheers !
